import type { SkillListItem } from '@/entities/skill/types'
import { cn } from '@/shared/lib/utils'
import { Badge } from '@/shared/ui/badge'
import { Checkbox } from '@/shared/ui/checkbox'
import DateTime from '@/shared/components/DateTime'
import { buildSkillGridTemplate } from './skillsColumns'
import { SkillActions } from './SkillActions'
import { categoryColorClass } from '@/entities/skill/categoryColors'

export function CategoryBadge({ category }: { category?: string }) {
  if (!category) return null
  return (
    <Badge variant="outline" className={cn('text-2xs border-transparent', categoryColorClass(category))}>
      {category}
    </Badge>
  )
}

export function CategoryBadges({ categories, fallback }: { categories?: string[]; fallback?: string }) {
  const list = categories && categories.length > 0 ? categories.filter(Boolean) : (fallback ? [fallback] : [])
  if (list.length === 0) return null
  return (
    <span className="flex flex-wrap gap-1 min-w-0">
      {list.map((cat) => (
        <Badge key={cat} variant="outline" className={cn('text-2xs border-transparent', categoryColorClass(cat))}>
          {cat}
        </Badge>
      ))}
    </span>
  )
}

export function OriginBadge({ sourceType }: { sourceType?: string }) {
  if (!sourceType) return null
  const isAi = sourceType === 'ai_generated'
  return (
    <Badge
      variant="outline"
      className={cn(
        'shrink-0 h-4 px-1.5 text-2xs border-transparent',
        isAi ? 'text-primary bg-primary/10' : 'text-muted-foreground bg-muted/60',
      )}
      title={isAi ? 'Generated by AI' : 'Created manually'}
    >
      {isAi ? 'AI' : 'Manual'}
    </Badge>
  )
}

export function SkillRow({
  skill,
  onViewDetails,
  onEdit,
  onDelete,
  onBreakDown,
  onMerge,
  showSelectColumn = false,
  selected = false,
  onToggleSelect,
  showRowNumberColumn = false,
  rowNumber,
}: {
  skill: SkillListItem
  onViewDetails: (id: number) => void
  onEdit: (id: number) => void
  onDelete: (id: number) => void
  onBreakDown: (id: number) => void
  onMerge: (id: number) => void
  showSelectColumn?: boolean
  selected?: boolean
  onToggleSelect?: (id: number) => void
  showRowNumberColumn?: boolean
  rowNumber?: number
}) {
  const confidence = skill.confidence != null ? Math.round(skill.confidence * 100) : null
  const demand = skill.market_relevance != null ? Math.round(skill.market_relevance * 100) : null

  const confidenceColor = confidence == null ? 'text-muted-foreground' : confidence >= 80 ? 'text-green-500' : confidence >= 50 ? 'text-yellow-500' : 'text-orange-500'
  const demandColor = demand == null ? 'text-muted-foreground' : demand >= 80 ? 'text-green-500' : demand >= 50 ? 'text-yellow-500' : 'text-orange-500'

  const gridTemplateColumns = buildSkillGridTemplate(showRowNumberColumn, showSelectColumn)

  return (
    <div
      className="group relative grid border-b border-border/40 hover:bg-muted/50 hover:ring-1 hover:ring-inset hover:ring-border/60 focus-within:bg-muted/50 cursor-pointer transition-colors items-center"
      style={{ gridTemplateColumns }}
      onClick={() => onViewDetails(skill.id)}
    >
      {showRowNumberColumn && (
        <div className="py-2 px-3 flex items-center justify-center">
          <span className="text-2xs text-muted-foreground tabular-nums">{rowNumber ?? ''}</span>
        </div>
      )}
      {showSelectColumn && (
        <div className="py-2 px-2 flex items-center justify-center" onClick={(e) => e.stopPropagation()}>
          <Checkbox
            checked={selected}
            onCheckedChange={() => onToggleSelect?.(skill.id)}
            aria-label={`Select ${skill.name}`}
          />
        </div>
      )}
      <div className="py-2 px-3 flex items-center">
        <div className="flex items-center gap-2 min-w-0">
          <span className="text-xs font-medium text-foreground truncate">{skill.name}</span>
          <OriginBadge sourceType={skill.source_type} />
          {skill.aliases.length > 0 && (
            <Badge variant="secondary" className="shrink-0 h-4 px-1.5 text-2xs text-muted-foreground">
              {skill.aliases.length} alias{skill.aliases.length !== 1 ? 'es' : ''}
            </Badge>
          )}
        </div>
      </div>
      <div className="py-2 px-3 flex items-center">
        <CategoryBadges categories={skill.categories} fallback={skill.category} />
      </div>
      <div className="py-2 px-3 flex items-center">
        <span className="text-xs font-semibold text-foreground">Lv.{skill.level}</span>
      </div>
      <div className="py-2 px-3 flex items-center">
        <span className="text-xs text-muted-foreground truncate block">{skill.roles || '—'}</span>
      </div>
      <div className="py-2 px-3 flex items-center">
        <span className={cn('text-xs font-semibold', demandColor)}>{demand != null ? `${demand}%` : '—'}</span>
      </div>
      <div className="py-2 px-3 flex items-center">
        <span className={cn('text-xs font-semibold', confidenceColor)}>{confidence != null ? `${confidence}%` : '—'}</span>
      </div>
      <div className="py-2 px-3 flex items-center">
        <DateTime value={skill.created_at} format="relative" className="text-2xs text-muted-foreground" />
      </div>
      <div className="py-2 px-3 flex items-center">
        <span className={cn('text-xs font-semibold', (skill.mention_count ?? 0) > 0 ? 'text-primary' : 'text-muted-foreground/50')}>
          {skill.mention_count ?? 0}
        </span>
      </div>
      <div className="absolute inset-y-0 right-1 flex items-center opacity-0 group-hover:opacity-100 transition-opacity" onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center bg-card ring-1 ring-border rounded-md shadow-sm px-1">
          <SkillActions
            onViewDetails={() => onViewDetails(skill.id)}
            onBreakDown={() => onBreakDown(skill.id)}
            onMerge={() => onMerge(skill.id)}
            onEdit={() => onEdit(skill.id)}
            onDelete={() => onDelete(skill.id)}
          />
        </div>
      </div>
    </div>
  )
}
