"""initial opportunity schema

Revision ID: opportunity_001
Revises: e2860ac259cf
Create Date: 2026-10-03 17:52:07.676909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'opportunity_001'
down_revision: Union[str, None] = 'e2860ac259cf'
branch_labels: Union[str, Sequence[str], None] = ('opportunity',)
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(bind, name: str, schema: str) -> bool:
    return sa.inspect(bind).has_table(name, schema=schema)


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS opportunity")
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists(bind, "opportunities", "opportunity"):
        op.create_table('opportunities',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('source_message_id', sa.String(), nullable=True),
        sa.Column('sender', sa.String(), nullable=True),
        sa.Column('sender_email', sa.String(), nullable=True),
        sa.Column('received_at', sa.String(), nullable=True),
        sa.Column('subject', sa.String(), nullable=True),
        sa.Column('raw_content', sa.Text(), nullable=False),
        sa.Column('content_hash', sa.String(length=64), nullable=False),
        sa.Column('extracted_urls', sa.Text(), nullable=False),
        sa.Column('extracted', sa.Text(), nullable=False),
        sa.Column('company_id', sa.String(length=36), nullable=True),
        sa.Column('company_name', sa.String(), nullable=True),
        sa.Column('job_id', sa.String(length=36), nullable=True),
        sa.Column('job_title', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('evaluation_status', sa.String(), nullable=False),
        sa.Column('fit_score', sa.Integer(), nullable=True),
        sa.Column('success_score', sa.Integer(), nullable=True),
        sa.Column('overall_score', sa.Integer(), nullable=True),
        sa.Column('recommendation', sa.String(), nullable=True),
        sa.Column('evaluation', sa.Text(), nullable=False),
        sa.Column('missing_information', sa.Text(), nullable=False),
        sa.Column('application_path', sa.Text(), nullable=False),
        sa.Column('next_action', sa.Text(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
        schema='opportunity'
        )
        op.create_index(op.f('ix_opportunity_opportunities_company_id'), 'opportunities', ['company_id'], unique=False, schema='opportunity')
        op.create_index(op.f('ix_opportunity_opportunities_content_hash'), 'opportunities', ['content_hash'], unique=False, schema='opportunity')
        op.create_index(op.f('ix_opportunity_opportunities_job_id'), 'opportunities', ['job_id'], unique=False, schema='opportunity')
        op.create_index(op.f('ix_opportunity_opportunities_source_message_id'), 'opportunities', ['source_message_id'], unique=False, schema='opportunity')
        op.create_index(op.f('ix_opportunity_opportunities_status'), 'opportunities', ['status'], unique=False, schema='opportunity')
        op.create_index(op.f('ix_opportunity_opportunities_user_id'), 'opportunities', ['user_id'], unique=False, schema='opportunity')
    if not _table_exists(bind, "opportunity_evaluations", "opportunity"):
        op.create_table('opportunity_evaluations',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('opportunity_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('evaluation_status', sa.String(), nullable=False),
        sa.Column('fit_score', sa.Integer(), nullable=True),
        sa.Column('success_score', sa.Integer(), nullable=True),
        sa.Column('overall_score', sa.Integer(), nullable=True),
        sa.Column('recommendation', sa.String(), nullable=True),
        sa.Column('snapshot', sa.Text(), nullable=False),
        sa.Column('created_at', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.opportunities.id'], name=op.f('fk_opportunity_evaluations_opportunity_id_opportunities')),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_evaluations')),
        schema='opportunity'
        )
        op.create_index(op.f('ix_opportunity_opportunity_evaluations_opportunity_id'), 'opportunity_evaluations', ['opportunity_id'], unique=False, schema='opportunity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opportunity_opportunity_evaluations_opportunity_id'), table_name='opportunity_evaluations', schema='opportunity')
    op.drop_table('opportunity_evaluations', schema='opportunity')
    op.drop_index(op.f('ix_opportunity_opportunities_user_id'), table_name='opportunities', schema='opportunity')
    op.drop_index(op.f('ix_opportunity_opportunities_status'), table_name='opportunities', schema='opportunity')
    op.drop_index(op.f('ix_opportunity_opportunities_source_message_id'), table_name='opportunities', schema='opportunity')
    op.drop_index(op.f('ix_opportunity_opportunities_job_id'), table_name='opportunities', schema='opportunity')
    op.drop_index(op.f('ix_opportunity_opportunities_content_hash'), table_name='opportunities', schema='opportunity')
    op.drop_index(op.f('ix_opportunity_opportunities_company_id'), table_name='opportunities', schema='opportunity')
    op.drop_table('opportunities', schema='opportunity')
    # ### end Alembic commands ###
